# Generated by Django 4.0.4 on 2022-04-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automania', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='published',
        ),
        migrations.RemoveField(
            model_name='order',
            name='realized',
        ),
    ]
