# Generated by Django 4.0.4 on 2022-04-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automania', '0003_order_date_order_published_order_realized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='user',
            new_name='published',
        ),
    ]
