# Generated by Django 4.0.4 on 2022-07-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automania', '0005_messeges'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadedMesseges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=128)),
                ('read', models.BooleanField(default=False)),
                ('data', models.DateField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automania.messeges')),
            ],
        ),
    ]
